name: Action on pull request
on:
  # Triggers the workflow on pull request events but only for default and protected branches
  pull_request:
    branches: main
jobs:
  analyze: 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    - uses: ./
      with:
        version: 1.8.10
        install-native: true
    - run: kotlinc -version
    - run: kotlinc-native -version
    - run: echo 'fun main() {println("Hello Kotlin/Native!")}' > hello.kt
    - run: kotlinc-native hello.kt
    - run: ./program.exe
      if: ${{ matrix.os == 'windows-latest' }}
    - run: ./program.kexe
      if: ${{ matrix.os != 'windows-latest' }}

    
